#cloud-config
ssh_keys:
  ecdsa_private: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
    1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQQ4azSXWvFNL2dabcJPFadrV90t5XTK
    jeIu702AGR7qjb/Y4Iuf4SZNz1GSCJN43thqEe46WydtccWxR//y7T+AAAAAuGsH9KNrB/
    SjAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDhrNJda8U0vZ1pt
    wk8Vp2tX3S3ldMqN4i7vTYAZHuqNv9jgi5/hJk3PUZIIk3je2GoR7jpbJ21xxbFH//LtP4
    AAAAAhAIfHN2qRzDx62zMVpWH29wY+curmfx3WGB8IkaGK+LwLAAAAGEhvc3RLZXkyMDE5
    MDQxMDExMDM1N2JzdAECAwQFBgc=
    -----END OPENSSH PRIVATE KEY-----
  ecdsa_public: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDhrNJda8U0vZ1ptwk8Vp2tX3S3ldMqN4i7vTYAZHuqNv9jgi5/hJk3PUZIIk3je2GoR7jpbJ21xxbFH//LtP4A= HostKey20190410110357bst
runcmd:
  - sed -i 's/[#]*Port 22/Port 7822/g' /etc/ssh/sshd_config
  #- sed -i 's/#HostKey \/etc\/ssh\/ssh_host_ed25519_key/HostKey \/etc\/ssh\/ssh_host_ed25519_key/g' /etc/ssh/sshd_config
  - /etc/init.d/ssh restart
