#cloud-config
ssh_keys:
  ed25519_private:
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBBrdbD1RLEZJZlyGikrAdjXLtB8dD/v+uaNBBbGH1ovQAAAKCe4gGDnuIB
    gwAAAAtzc2gtZWQyNTUxOQAAACBBrdbD1RLEZJZlyGikrAdjXLtB8dD/v+uaNBBbGH1ovQ
    AAAEAn3rMPwTAIjKofy5FztcZc5tDod//hiPb+rHq2ikhFfEGt1sPVEsRklmXIaKSsB2Nc
    u0Hx0P+/65o0EFsYfWi9AAAAGEhvc3RLZXkyMDE5MDQxMDEwNTk1MGJzdAECAwQF
    -----END OPENSSH PRIVATE KEY-----
  ed25519_public:
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEGt1sPVEsRklmXIaKSsB2Ncu0Hx0P+/65o0EFsYfWi9 HostKey20190410105950bst
runcmd:
  - sed -i 's/[#]*Port 22/Port 7822/g' /etc/ssh/sshd_config
  - sed -i 's/#HostKey \/etc\/ssh\/ssh_host_ed25519_key/HostKey \/etc\/ssh\/ssh_host_ed25519_key/g' /etc/ssh/sshd_config
