#cloud-config
ssh_keys:
  rsa_private: |
    -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAxeycDe4sRN1zFCYOv3fZfaNIAF3uISoFWpUbCn2cAzGO6Van5fIV
GPA19yfCqxVcMYoxM43rSdEudlT0RnyuQWBUXx+vfZfIhkr5Q2m9UKmX0zAobJ9kcmi4GB
AABkLUW+ax6DHvm6WiTLHe+/ztKJw4IcE8w2j+LJwFx6C1CKzi86lfsVzvYOP6bbp/MptV
7JVkE1OQQwwLQBJG4NSlUb/qi1J/FHfsRp7X+BiFQrGWxW6s9a7PT6yaBNc8koEfdShGht
Ftz4fTEBhdF3q5OsG5AK+5j90RzKYv235uXbXcm4dVLbc+bQ59If+AJ6qTOxXIjQD8jQrW
ignAbsBY7oGn7o0ymsC+XHUnpFqnBaQ6KouiYboM2hWG1XT90Ga+Gyliq+IT7a1ghZnt5I
2rXkqmyCTuHM2tK6tXBp5NXQpXHk8UsXbTRKSsMGh3xib5GEWBK3m58/zBPYwjjf1ASeq1
lQmpfBf9CovgTDlAqGsl00i4rhNtzeZ5HwIxpiBmHfXBVnAgTQ7cW9QMqr8ADfgvAFo5us
BOPz1cjFfVcz3OSHcn/CpXI9RixGO2sEg81UZPI/efEKtDolN5zpUvT0Es7iO6cj+SHq7n
4BTN8mOJyqpm8lLkPQRh0aAFNT2jPZk37G0Hac6yHEq/ACuexetnDt9yFmAEGFkHo75PTh
UAAAdQU8Knw1PCp8MAAAAHc3NoLXJzYQAAAgEAxeycDe4sRN1zFCYOv3fZfaNIAF3uISoF
WpUbCn2cAzGO6Van5fIVGPA19yfCqxVcMYoxM43rSdEudlT0RnyuQWBUXx+vfZfIhkr5Q2
m9UKmX0zAobJ9kcmi4GBAABkLUW+ax6DHvm6WiTLHe+/ztKJw4IcE8w2j+LJwFx6C1CKzi
86lfsVzvYOP6bbp/MptV7JVkE1OQQwwLQBJG4NSlUb/qi1J/FHfsRp7X+BiFQrGWxW6s9a
7PT6yaBNc8koEfdShGhtFtz4fTEBhdF3q5OsG5AK+5j90RzKYv235uXbXcm4dVLbc+bQ59
If+AJ6qTOxXIjQD8jQrWignAbsBY7oGn7o0ymsC+XHUnpFqnBaQ6KouiYboM2hWG1XT90G
a+Gyliq+IT7a1ghZnt5I2rXkqmyCTuHM2tK6tXBp5NXQpXHk8UsXbTRKSsMGh3xib5GEWB
K3m58/zBPYwjjf1ASeq1lQmpfBf9CovgTDlAqGsl00i4rhNtzeZ5HwIxpiBmHfXBVnAgTQ
7cW9QMqr8ADfgvAFo5usBOPz1cjFfVcz3OSHcn/CpXI9RixGO2sEg81UZPI/efEKtDolN5
zpUvT0Es7iO6cj+SHq7n4BTN8mOJyqpm8lLkPQRh0aAFNT2jPZk37G0Hac6yHEq/ACuexe
tnDt9yFmAEGFkHo75PThUAAAADAQABAAACAG7Y9Q1YNrLa03iVV+0j0krrB4gtExC/1//D
QkG914JyXveP8Lh3vBkbbx3cxsnKTLfyDVwyP3Q4Ey1yptxTN8Sljps3w7EzMLsFglSfA8
gJM16zufAb1MW+oFvZminng8d0jG7eiLNDMIKDm77FCI2V8Fn3P3CxfKi/OP10o+8X5INS
eKV8xxQcmkSaDmLpXFYD1Oh+BG2IcUSQ9+EzNuNx+InOyh1MjKeAjrQEB54yl547PeLa5I
Baymero+DpMBUNWXJoGHgCOdLp0jk0Ikkl9dbMk8Ber3lOGb90L5uMHuF8CdhwqCWr16kS
z1Nn1M1ihc9ynf7f8wecLonYb/UnsC6XHv5pjdnFG5lHIiKd0PEnoql+il0cMkWpcPCJ0H
vF8NjXgPIGPrsUJOUOesVJemgjB9he9+bns2LSYoFjrT2hXAXRsF7GRMtirUI8cbsGaAAh
HjTyUc02OskNsdLefqQpWmkUYoShm2hjKB/QIr874GqESkKwyivhgHQS21meDzZe/+nejR
RVEYHS8PzhZ59OINbAqivRq2uWO5VoV/FYYYloeJDnxzn6cqtmneZHye7QownFavef4p8P
AHfci0F3jEmf942R7fbw3uzHACC/gfe34AlhxQvbOdI94a8SksRuwOOha0Dr4dxnzMDaqp
4TsC/DHfxdbxCgGnwBAAABAQDSiqfqUKyb2miwW5FOmBEB/pqMG9f4UHXEivCbW92eybpr
WUl2QHZqbNNu3rbpZOc409YDZ2Tpa1LXjLv17xfwnt9xynHcbziISzPkKNnC8y1+KTO9vn
e6X7Bx640NUoH75pHEHH+/7mqhp3l9mAyXn7995csQZ3VIQaNJ1JL2ic+aYdGv307t+FBO
wRdSLBx5w+Hrv6s7X+rpilqqS9SuEoxMzAx5iqDaSrSVlI3yhiBTJY2h1lZw4wj95w1ZT5
8ZTpXd5Pxk931qeTR+A46898CUId6fBajn8PGite9yISkKGN0Iu6RkxMVsNeYPRjTaK0xM
5rMUwG9ofNK49qy4AAABAQDm/XXHeZCta8HXyNsK6rqy14rOdB/6sJRr51WXJ64BbVsLcD
ubb7t7VFTBYrl0LwVZj4ZsDtD2u1XyziLtUh1Jka4OFvoPw0Jph9IUnJ2nt/lCgkpE9MAM
KOBeSeG9A+liA3j5BaOz18zG3uxcwGXah3cV6N0yMIM7ff5ISNwIgcSs5312LPF/W4/R/r
a0jg7uU6Lmc2WFdN9rxWwghGYf6fFGBzSPoPANJMCdHnrVNm8BDYignLT/7ZoMp5wPZVVp
BoLxiHkbCc6fvEfdog3SXz5D76twyPykr9BDpLMzgqp2HD4GZhveyAjPLVHuIG3E9NcCGu
PfZIz/2C/2wQMdAAABAQDbWqMgsKGQADkr1xj4uRmeOMhpWIsrPxB/VSn3yssqKacvttrn
KLR9JWbzGoEdukGzRONUjE0hmaIqoAcjcPS3vddEKPcjujBGDbP7E9B9/8kjVlMxbx7YOG
UocBvJiLRXBnUP+vv/oPASAYcnJ6Hr4sXHA1QVUjkSAWaA6Ny06SwF1QSfZyHDyvzfMix6
IfvJGaFfr8Gwr/80v4rjyw40kHb+jiF7AT2YpnSy3ZSTUqQOA9kzntqbHyXipgNOcN/5m2
J42c37O+MTcSsVUS6gB602PNyv8izxj8MWs6oMcYCxttyXP6RLw+Tlyd3viThnwtc8GOcn
BxvI7J6/481ZAAAAGEhvc3RLZXkyMDE5MDQxMDExMDYwM2JzdAEC
-----END OPENSSH PRIVATE KEY-----
  rsa_public: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDF7JwN7ixE3XMUJg6/d9l9o0gAXe4hKgValRsKfZwDMY7pVqfl8hUY8DX3J8KrFVwxijEzjetJ0S52VPRGfK5BYFRfH699l8iGSvlDab1QqZfTMChsn2RyaLgYEAAGQtRb5rHoMe+bpaJMsd77/O0onDghwTzDaP4snAXHoLUIrOLzqV+xXO9g4/ptun8ym1XslWQTU5BDDAtAEkbg1KVRv+qLUn8Ud+xGntf4GIVCsZbFbqz1rs9PrJoE1zySgR91KEaG0W3Ph9MQGF0Xerk6wbkAr7mP3RHMpi/bfm5dtdybh1Uttz5tDn0h/4AnqpM7FciNAPyNCtaKCcBuwFjugafujTKawL5cdSekWqcFpDoqi6JhugzaFYbVdP3QZr4bKWKr4hPtrWCFme3kjateSqbIJO4cza0rq1cGnk1dClceTxSxdtNEpKwwaHfGJvkYRYErebnz/ME9jCON/UBJ6rWVCal8F/0Ki+BMOUCoayXTSLiuE23N5nkfAjGmIGYd9cFWcCBNDtxb1AyqvwAN+C8AWjm6wE4/PVyMV9VzPc5Idyf8Klcj1GLEY7awSDzVRk8j958Qq0OiU3nOlS9PQSzuI7pyP5IerufgFM3yY4nKqmbyUuQ9BGHRoAU1PaM9mTfsbQdpzrIcSr8AK57F62cO33IWYAQYWQejvk9OFQ== HostKey20190410110603bst
locale: en_GB.UTF-8
timezone: Europe/London
#package_update: true    # Implied with `package_upgrade: true`
package_upgrade: true
package_reboot_if_required: true
users:
# Create new user `steve`
  - name: steve
    groups: sudo, www-data
    lock_passwd: false
    shell: /bin/bash
    passwd: $6$UnXq642da9EfkQfH$TNr4OeOsSzye7OLxzS79tRs5kSyE3LyhFQPSjLWEdsDC.1TA5vARJt7TrDdwqCcpHrEYrXl02vycJVFx.GvZd.
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFuA6ESIAd/5QzlArU9/o/dwqy8/23xg6oEX6bSYcX7f steve20190408094644bst
runcmd:
  - sed -i 's/[# ]*set tabsize 8/set tabsize 4/g' /etc/nanorc
# Configure SSH
  - sed -i 's/[#]*Port 22/Port 7822/g' /etc/ssh/sshd_config
  - sed -i 's/#HostKey \/etc\/ssh\/ssh_host_ed25519_key/HostKey \/etc\/ssh\/ssh_host_ed25519_key/g' /etc/ssh/sshd_config
  - sed -i 's/[#]*PermitRootLogin yes/PermitRootLogin prohibit-password/g' /etc/ssh/sshd_config
  #- sed -i '/prohibit-password/! s/[#]*PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
  - sed -i 's/[#]*PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
  - /etc/init.d/ssh restart
# Configure Firewall
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow 7822/tcp
  #- ufw allow 10000/tcp    # For Webmin
  - ufw enable
# Configure .bashrc for `root`
  - sed -i 's/($debian_chroot)}\\u\@\\h:\\/($debian_chroot)}\\u\@\`curl -s http:\/\/icanhazip.com\`:\\/g' /root/.bashrc
  - sed -i 's/($debian_chroot)}\\\[\\033\[01;32m\\\]\\u\@\\h/($debian_chroot)}\\\[\\033\[01;32m\\\]\\u\@\`curl -s http:\/\/icanhazip.com\`/g' /root/.bashrc
# Configure .bashrc for `steve`
  - sed -i -E 's/secure_path="(.*)"/secure_path="\1:\/home\/steve\/scripts"/g' /etc/sudoers
  - sed -i 's/($debian_chroot)}\\u\@\\h:\\/($debian_chroot)}\\u\@\`curl -s http:\/\/icanhazip.com\`:\\/g' /home/steve/.bashrc
  - sed -i 's/($debian_chroot)}\\\[\\033\[01;32m\\\]\\u\@\\h/($debian_chroot)}\\\[\\033\[01;32m\\\]\\u\@\`curl -s http:\/\/icanhazip.com\`/g' /home/steve/.bashrc
  - echo "alias wp-install='bash /home/steve/scripts/install-wordpress.sh'" >> /home/steve/.bashrc
  - echo "alias wp-remove='bash /home/steve/scripts/remove-wordpress.sh'" >> /home/steve/.bashrc
  - echo "alias vhost-add='bash /home/steve/scripts/add-vhost.sh'" >> /home/steve/.bashrc
  - echo "alias vhost-del='bash /home/steve/scripts/delete-vhost.sh'" >> /home/steve/.bashrc
  - echo "alias update='sudo -- sh -c \"apt update; apt upgrade -y; apt dist-upgrade -y; apt autoremove -y; apt autoclean -y\"'" >> /home/steve/.bashrc
  - echo "alias shutdown-r='sudo shutdown -r now'" >> /home/steve/.bashrc
  - export PATH=$PATH:/home/steve/scripts
# Force password change for `steve` on initial login
  - chage -d 0 steve
